#!/usr/bin/env python3
"""Generate a properly-formatted literature benchmark CSV."""
import pandas as pd
import os

OUTPUT = "/Users/mallorymalz/Documents/chelator_ml_project/data/literature_benchmark_data.csv"

data = [
    {"study_id": "NAGHIPOUR_1", "citation": "Naghipour et al. (2016) J Environ Manage", "doi": "10.1016/j.jenvman.2016.07.073", "year": 2016, "study_type": "column", "soil_texture": "sandy loam", "ph": 7.0, "om_percent": None, "cec_cmol_kg": None, "ec_dS_m": None, "na_mg_L": None, "salinity_description": None, "moisture_description": "slurry", "pb_mg_kg": 500, "cu_mg_kg": None, "zn_mg_kg": 500, "cd_mg_kg": None, "metal": "pb", "chelator_used": "EDTA", "chelator_dose": 0.1, "dose_unit": "mol/L", "contact_time_hr": 24, "liquid_solid_ratio": None, "observed_extraction_pct": 85.3, "observed_free_pct": None, "observed_best_chelator": "EDTA", "notes": "Synthetic contaminated soil; 3 pore volumes; single metal 500 mg/kg"},
    {"study_id": "NAGHIPOUR_2", "citation": "Naghipour et al. (2016) J Environ Manage", "doi": "10.1016/j.jenvman.2016.07.073", "year": 2016, "study_type": "column", "soil_texture": "sandy loam", "ph": 7.0, "om_percent": None, "cec_cmol_kg": None, "ec_dS_m": None, "na_mg_L": None, "salinity_description": None, "moisture_description": "slurry", "pb_mg_kg": None, "cu_mg_kg": None, "zn_mg_kg": None, "cd_mg_kg": 500, "metal": "cd", "chelator_used": "EDTA", "chelator_dose": 0.1, "dose_unit": "mol/L", "contact_time_hr": 24, "liquid_solid_ratio": None, "observed_extraction_pct": 83.2, "observed_free_pct": None, "observed_best_chelator": "EDTA", "notes": "Same study; Cd extraction"},
    {"study_id": "NAGHIPOUR_3", "citation": "Naghipour et al. (2016) J Environ Manage", "doi": "10.1016/j.jenvman.2016.07.073", "year": 2016, "study_type": "column", "soil_texture": "sandy loam", "ph": 7.0, "om_percent": None, "cec_cmol_kg": None, "ec_dS_m": None, "na_mg_L": None, "salinity_description": None, "moisture_description": "slurry", "pb_mg_kg": None, "cu_mg_kg": None, "zn_mg_kg": 500, "cd_mg_kg": None, "metal": "zn", "chelator_used": "EDTA", "chelator_dose": 0.1, "dose_unit": "mol/L", "contact_time_hr": 24, "liquid_solid_ratio": None, "observed_extraction_pct": 69.7, "observed_free_pct": None, "observed_best_chelator": "EDTA", "notes": "Same study; Zn hardest to extract"},
    {"study_id": "NAGHIPOUR_4", "citation": "Naghipour et al. (2016) J Environ Manage", "doi": "10.1016/j.jenvman.2016.07.073", "year": 2016, "study_type": "column", "soil_texture": "sandy loam", "ph": 7.0, "om_percent": None, "cec_cmol_kg": None, "ec_dS_m": None, "na_mg_L": None, "salinity_description": None, "moisture_description": "slurry", "pb_mg_kg": 500, "cu_mg_kg": None, "zn_mg_kg": 500, "cd_mg_kg": None, "metal": "pb", "chelator_used": "NTA", "chelator_dose": 0.1, "dose_unit": "mol/L", "contact_time_hr": 24, "liquid_solid_ratio": None, "observed_extraction_pct": 21.8, "observed_free_pct": None, "observed_best_chelator": "EDTA", "notes": "NTA much less effective than EDTA for Pb"},
    {"study_id": "NAGHIPOUR_5", "citation": "Naghipour et al. (2016) J Environ Manage", "doi": "10.1016/j.jenvman.2016.07.073", "year": 2016, "study_type": "column", "soil_texture": "sandy loam", "ph": 7.0, "om_percent": None, "cec_cmol_kg": None, "ec_dS_m": None, "na_mg_L": None, "salinity_description": None, "moisture_description": "slurry", "pb_mg_kg": None, "cu_mg_kg": None, "zn_mg_kg": None, "cd_mg_kg": 500, "metal": "cd", "chelator_used": "NTA", "chelator_dose": 0.1, "dose_unit": "mol/L", "contact_time_hr": 24, "liquid_solid_ratio": None, "observed_extraction_pct": 83.6, "observed_free_pct": None, "observed_best_chelator": "NTA", "notes": "NTA comparable to EDTA for Cd"},
    {"study_id": "NAGHIPOUR_6", "citation": "Naghipour et al. (2016) J Environ Manage", "doi": "10.1016/j.jenvman.2016.07.073", "year": 2016, "study_type": "column", "soil_texture": "sandy loam", "ph": 7.0, "om_percent": None, "cec_cmol_kg": None, "ec_dS_m": None, "na_mg_L": None, "salinity_description": None, "moisture_description": "slurry", "pb_mg_kg": None, "cu_mg_kg": None, "zn_mg_kg": 500, "cd_mg_kg": None, "metal": "zn", "chelator_used": "NTA", "chelator_dose": 0.1, "dose_unit": "mol/L", "contact_time_hr": 24, "liquid_solid_ratio": None, "observed_extraction_pct": 24.5, "observed_free_pct": None, "observed_best_chelator": "EDTA", "notes": "NTA much weaker for Zn"},
    {"study_id": "TANDY_1", "citation": "Tandy et al. (2004) Environ Sci Technol", "doi": "10.1021/es0348750", "year": 2004, "study_type": "batch", "soil_texture": "loam", "ph": 7.0, "om_percent": None, "cec_cmol_kg": None, "ec_dS_m": None, "na_mg_L": None, "salinity_description": "non-saline", "moisture_description": "slurry", "pb_mg_kg": None, "cu_mg_kg": 250, "zn_mg_kg": 650, "cd_mg_kg": None, "metal": "cu", "chelator_used": "EDTA", "chelator_dose": 1, "dose_unit": "mmol/kg", "contact_time_hr": 24, "liquid_solid_ratio": None, "observed_extraction_pct": 18.0, "observed_free_pct": None, "observed_best_chelator": "EDDS", "notes": "Equimolar chelator:metal; Ca competition reduced EDTA efficiency for Cu"},
    {"study_id": "TANDY_2", "citation": "Tandy et al. (2004) Environ Sci Technol", "doi": "10.1021/es0348750", "year": 2004, "study_type": "batch", "soil_texture": "loam", "ph": 7.0, "om_percent": None, "cec_cmol_kg": None, "ec_dS_m": None, "na_mg_L": None, "salinity_description": "non-saline", "moisture_description": "slurry", "pb_mg_kg": None, "cu_mg_kg": 250, "zn_mg_kg": 650, "cd_mg_kg": None, "metal": "cu", "chelator_used": "NTA", "chelator_dose": 1, "dose_unit": "mmol/kg", "contact_time_hr": 24, "liquid_solid_ratio": None, "observed_extraction_pct": 25.0, "observed_free_pct": None, "observed_best_chelator": "EDDS", "notes": "NTA outperformed EDTA for Cu at pH 7 equimolar"},
    {"study_id": "TANDY_3", "citation": "Tandy et al. (2004) Environ Sci Technol", "doi": "10.1021/es0348750", "year": 2004, "study_type": "batch", "soil_texture": "loam", "ph": 7.0, "om_percent": None, "cec_cmol_kg": None, "ec_dS_m": None, "na_mg_L": None, "salinity_description": "non-saline", "moisture_description": "slurry", "pb_mg_kg": None, "cu_mg_kg": 250, "zn_mg_kg": 650, "cd_mg_kg": None, "metal": "zn", "chelator_used": "NTA", "chelator_dose": 1, "dose_unit": "mmol/kg", "contact_time_hr": 24, "liquid_solid_ratio": None, "observed_extraction_pct": 22.0, "observed_free_pct": None, "observed_best_chelator": "NTA", "notes": "NTA best for Zn extraction at equimolar"},
    {"study_id": "TANDY_4", "citation": "Tandy et al. (2004) Environ Sci Technol", "doi": "10.1021/es0348750", "year": 2004, "study_type": "batch", "soil_texture": "loam", "ph": 7.0, "om_percent": None, "cec_cmol_kg": None, "ec_dS_m": None, "na_mg_L": None, "salinity_description": "non-saline", "moisture_description": "slurry", "pb_mg_kg": None, "cu_mg_kg": 250, "zn_mg_kg": 650, "cd_mg_kg": None, "metal": "zn", "chelator_used": "EDTA", "chelator_dose": 1, "dose_unit": "mmol/kg", "contact_time_hr": 24, "liquid_solid_ratio": None, "observed_extraction_pct": 15.0, "observed_free_pct": None, "observed_best_chelator": "NTA", "notes": "EDTA less effective than NTA for Zn"},
    {"study_id": "TANDY_5", "citation": "Tandy et al. (2004) Environ Sci Technol", "doi": "10.1021/es0348750", "year": 2004, "study_type": "batch", "soil_texture": "loam", "ph": 7.0, "om_percent": None, "cec_cmol_kg": None, "ec_dS_m": None, "na_mg_L": None, "salinity_description": "non-saline", "moisture_description": "slurry", "pb_mg_kg": 1500, "cu_mg_kg": 250, "zn_mg_kg": 650, "cd_mg_kg": None, "metal": "pb", "chelator_used": "EDTA", "chelator_dose": 1, "dose_unit": "mmol/kg", "contact_time_hr": 24, "liquid_solid_ratio": None, "observed_extraction_pct": 45.0, "observed_free_pct": None, "observed_best_chelator": "EDTA", "notes": "EDTA strongest for Pb due to high stability constant"},
    {"study_id": "TANDY_6", "citation": "Tandy et al. (2004) Environ Sci Technol", "doi": "10.1021/es0348750", "year": 2004, "study_type": "batch", "soil_texture": "loam", "ph": 7.0, "om_percent": None, "cec_cmol_kg": None, "ec_dS_m": None, "na_mg_L": None, "salinity_description": "non-saline", "moisture_description": "slurry", "pb_mg_kg": 1500, "cu_mg_kg": 250, "zn_mg_kg": 650, "cd_mg_kg": None, "metal": "pb", "chelator_used": "NTA", "chelator_dose": 1, "dose_unit": "mmol/kg", "contact_time_hr": 24, "liquid_solid_ratio": None, "observed_extraction_pct": 30.0, "observed_free_pct": None, "observed_best_chelator": "EDTA", "notes": "NTA weaker than EDTA for Pb"},
    {"study_id": "HASEGAWA_1", "citation": "Hasegawa et al. (2019) Appl Geochem", "doi": "10.1016/j.apgeochem.2019.104397", "year": 2019, "study_type": "batch", "soil_texture": "loam", "ph": 5.0, "om_percent": None, "cec_cmol_kg": None, "ec_dS_m": None, "na_mg_L": None, "salinity_description": None, "moisture_description": "slurry", "pb_mg_kg": 500, "cu_mg_kg": None, "zn_mg_kg": None, "cd_mg_kg": None, "metal": "pb", "chelator_used": "EDTA", "chelator_dose": 10, "dose_unit": "mmol/kg", "contact_time_hr": 24, "liquid_solid_ratio": None, "observed_extraction_pct": 85.0, "observed_free_pct": None, "observed_best_chelator": "EDTA", "notes": "pH 5 maximum extraction; real contaminated soil"},
    {"study_id": "HASEGAWA_2", "citation": "Hasegawa et al. (2019) Appl Geochem", "doi": "10.1016/j.apgeochem.2019.104397", "year": 2019, "study_type": "batch", "soil_texture": "loam", "ph": 7.0, "om_percent": None, "cec_cmol_kg": None, "ec_dS_m": None, "na_mg_L": None, "salinity_description": None, "moisture_description": "slurry", "pb_mg_kg": 500, "cu_mg_kg": None, "zn_mg_kg": None, "cd_mg_kg": None, "metal": "pb", "chelator_used": "EDTA", "chelator_dose": 10, "dose_unit": "mmol/kg", "contact_time_hr": 24, "liquid_solid_ratio": None, "observed_extraction_pct": 65.0, "observed_free_pct": None, "observed_best_chelator": "EDTA", "notes": "Lower extraction at pH 7 than pH 5"},
    {"study_id": "HASEGAWA_3", "citation": "Hasegawa et al. (2019) Appl Geochem", "doi": "10.1016/j.apgeochem.2019.104397", "year": 2019, "study_type": "batch", "soil_texture": "loam", "ph": 5.0, "om_percent": None, "cec_cmol_kg": None, "ec_dS_m": None, "na_mg_L": None, "salinity_description": None, "moisture_description": "slurry", "pb_mg_kg": None, "cu_mg_kg": 200, "zn_mg_kg": None, "cd_mg_kg": None, "metal": "cu", "chelator_used": "EDTA", "chelator_dose": 10, "dose_unit": "mmol/kg", "contact_time_hr": 24, "liquid_solid_ratio": None, "observed_extraction_pct": 70.0, "observed_free_pct": None, "observed_best_chelator": "DTPA", "notes": "DTPA slightly better than EDTA for Cu"},
    {"study_id": "HASEGAWA_4", "citation": "Hasegawa et al. (2019) Appl Geochem", "doi": "10.1016/j.apgeochem.2019.104397", "year": 2019, "study_type": "batch", "soil_texture": "loam", "ph": 5.0, "om_percent": None, "cec_cmol_kg": None, "ec_dS_m": None, "na_mg_L": None, "salinity_description": None, "moisture_description": "slurry", "pb_mg_kg": None, "cu_mg_kg": None, "zn_mg_kg": 400, "cd_mg_kg": None, "metal": "zn", "chelator_used": "EDTA", "chelator_dose": 10, "dose_unit": "mmol/kg", "contact_time_hr": 24, "liquid_solid_ratio": None, "observed_extraction_pct": 55.0, "observed_free_pct": None, "observed_best_chelator": "DTPA", "notes": "Zn harder to extract than Pb or Cu"},
    {"study_id": "LABANOWSKI_1", "citation": "Labanowski et al. (2008) Environ Pollut", "doi": "10.1016/j.envpol.2007.06.054", "year": 2008, "study_type": "batch", "soil_texture": "sandy loam", "ph": 7.2, "om_percent": 2.1, "cec_cmol_kg": None, "ec_dS_m": None, "na_mg_L": None, "salinity_description": "non-saline", "moisture_description": "slurry", "pb_mg_kg": 7500, "cu_mg_kg": None, "zn_mg_kg": 3100, "cd_mg_kg": None, "metal": "pb", "chelator_used": "EDTA", "chelator_dose": 0.05, "dose_unit": "mol/L", "contact_time_hr": 48, "liquid_solid_ratio": 10, "observed_extraction_pct": None, "observed_free_pct": None, "observed_best_chelator": "EDTA", "notes": "EDTA extracted 3x more Pb than citrate"},
    {"study_id": "LABANOWSKI_2", "citation": "Labanowski et al. (2008) Environ Pollut", "doi": "10.1016/j.envpol.2007.06.054", "year": 2008, "study_type": "batch", "soil_texture": "sandy loam", "ph": 7.2, "om_percent": 2.1, "cec_cmol_kg": None, "ec_dS_m": None, "na_mg_L": None, "salinity_description": "non-saline", "moisture_description": "slurry", "pb_mg_kg": 7500, "cu_mg_kg": None, "zn_mg_kg": 3100, "cd_mg_kg": None, "metal": "pb", "chelator_used": "Citrate", "chelator_dose": 0.05, "dose_unit": "mol/L", "contact_time_hr": 48, "liquid_solid_ratio": 10, "observed_extraction_pct": None, "observed_free_pct": None, "observed_best_chelator": "EDTA", "notes": "Citrate much weaker for Pb than EDTA"},
    {"study_id": "LABANOWSKI_3", "citation": "Labanowski et al. (2008) Environ Pollut", "doi": "10.1016/j.envpol.2007.06.054", "year": 2008, "study_type": "batch", "soil_texture": "sandy loam", "ph": 7.2, "om_percent": 2.1, "cec_cmol_kg": None, "ec_dS_m": None, "na_mg_L": None, "salinity_description": "non-saline", "moisture_description": "slurry", "pb_mg_kg": None, "cu_mg_kg": None, "zn_mg_kg": 3100, "cd_mg_kg": None, "metal": "zn", "chelator_used": "Citrate", "chelator_dose": 0.05, "dose_unit": "mol/L", "contact_time_hr": 48, "liquid_solid_ratio": 10, "observed_extraction_pct": None, "observed_free_pct": None, "observed_best_chelator": "Citrate", "notes": "Citrate proportionally better for Zn than for Pb"},
    {"study_id": "MEERS_1", "citation": "Meers et al. (2005) Int J Phytoremediation", "doi": "10.1080/16226510500214903", "year": 2005, "study_type": "batch", "soil_texture": "silt loam", "ph": 7.8, "om_percent": 3.8, "cec_cmol_kg": None, "ec_dS_m": None, "na_mg_L": None, "salinity_description": "non-saline", "moisture_description": "field capacity", "pb_mg_kg": 1200, "cu_mg_kg": 85, "zn_mg_kg": None, "cd_mg_kg": 3.2, "metal": "pb", "chelator_used": "EDTA", "chelator_dose": 10, "dose_unit": "mmol/kg", "contact_time_hr": 168, "liquid_solid_ratio": None, "observed_extraction_pct": 35.0, "observed_free_pct": None, "observed_best_chelator": "EDTA", "notes": "Calcareous soil; EDTA mobilized metals persistently"},
    {"study_id": "MEERS_2", "citation": "Meers et al. (2005) Int J Phytoremediation", "doi": "10.1080/16226510500214903", "year": 2005, "study_type": "batch", "soil_texture": "silt loam", "ph": 7.8, "om_percent": 3.8, "cec_cmol_kg": None, "ec_dS_m": None, "na_mg_L": None, "salinity_description": "non-saline", "moisture_description": "field capacity", "pb_mg_kg": 1200, "cu_mg_kg": 85, "zn_mg_kg": None, "cd_mg_kg": 3.2, "metal": "pb", "chelator_used": "Citrate", "chelator_dose": 250, "dose_unit": "mmol/kg", "contact_time_hr": 168, "liquid_solid_ratio": None, "observed_extraction_pct": 15.0, "observed_free_pct": None, "observed_best_chelator": "EDTA", "notes": "Citrate needed much higher dose; rapid biodegradation"},
    {"study_id": "MEERS_3", "citation": "Meers et al. (2005) Int J Phytoremediation", "doi": "10.1080/16226510500214903", "year": 2005, "study_type": "batch", "soil_texture": "silt loam", "ph": 7.8, "om_percent": 3.8, "cec_cmol_kg": None, "ec_dS_m": None, "na_mg_L": None, "salinity_description": "non-saline", "moisture_description": "field capacity", "pb_mg_kg": 1200, "cu_mg_kg": 85, "zn_mg_kg": None, "cd_mg_kg": 3.2, "metal": "cd", "chelator_used": "EDTA", "chelator_dose": 10, "dose_unit": "mmol/kg", "contact_time_hr": 168, "liquid_solid_ratio": None, "observed_extraction_pct": 25.0, "observed_free_pct": None, "observed_best_chelator": "EDTA", "notes": "Cd extraction lower than Pb"},
    {"study_id": "ALABOUDI_1", "citation": "Alaboudi et al. (2019) Pol J Environ Stud", "doi": None, "year": 2019, "study_type": "batch", "soil_texture": "loam", "ph": 6.1, "om_percent": None, "cec_cmol_kg": None, "ec_dS_m": None, "na_mg_L": None, "salinity_description": "non-saline", "moisture_description": "slurry", "pb_mg_kg": 200, "cu_mg_kg": None, "zn_mg_kg": None, "cd_mg_kg": None, "metal": "pb", "chelator_used": "EDTA", "chelator_dose": 0.25, "dose_unit": "mol/L", "contact_time_hr": 1, "liquid_solid_ratio": 2.5, "observed_extraction_pct": 75.0, "observed_free_pct": None, "observed_best_chelator": "EDTA", "notes": "Australian agricultural soil; artificially contaminated"},
    {"study_id": "ALABOUDI_2", "citation": "Alaboudi et al. (2019) Pol J Environ Stud", "doi": None, "year": 2019, "study_type": "batch", "soil_texture": "loam", "ph": 6.1, "om_percent": None, "cec_cmol_kg": None, "ec_dS_m": None, "na_mg_L": None, "salinity_description": "non-saline", "moisture_description": "slurry", "pb_mg_kg": 600, "cu_mg_kg": None, "zn_mg_kg": None, "cd_mg_kg": None, "metal": "pb", "chelator_used": "EDTA", "chelator_dose": 0.25, "dose_unit": "mol/L", "contact_time_hr": 1, "liquid_solid_ratio": 2.5, "observed_extraction_pct": 50.0, "observed_free_pct": None, "observed_best_chelator": "EDTA", "notes": "Higher contamination reduced extraction efficiency"},
]

df = pd.DataFrame(data)
df.to_csv(OUTPUT, index=False)
print(f"Wrote {len(df)} rows to {OUTPUT}")
print(f"Columns: {list(df.columns)}")
print(f"chelator_used values: {df['chelator_used'].unique().tolist()}")
print(f"metal values: {df['metal'].unique().tolist()}")
print(f"ph values: {df['ph'].unique().tolist()}")
print("CSV is ready. Now run: python3 tier2_benchmark_final.py")
